#!/bin/python3

import sys


n,k = input().strip().split(' ')
n,k = [int(n),int(k)]
x,y = input().strip().split(' ')
x,y = [int(x)-1,int(y)-1]
a=[]
p=x
w=x
e=x
c=x
g=x
j=x
l=x
q=y
r=y
t=y
v=y
b=y
h=y
k=y
count=0
for a_i in range(n):
        a_t = [0 for j in range(n)]
        a.append(a_t)
for i in range(k):
    x_,y_= map(int,input().strip().split(' '))
    a[x_-1][y_-1]=1

for i in range(n):
    if  p-1>=0:
        if a[p-1][q]==0:
            count=count+1
            p=p-1
        elif a[p-1][q]==1:
            break
    if  w+1<=n-1:
        if a[w+1][q]==0:
            count=count+1
            w=w+1
        elif a[w+1][q]==1:
            break
    if  r+1<=n-1:
        if a[e][r+1]==0:
            count=count+1
            r=r+1
        elif a[e][r+1]==1:
            break
    if  t-1>=0:
        if a[e][t-1]==0:
            count=count+1
            t=t-1
        elif a[e][t-1]==1:
            break
    if c+1<=n-1 and v+1<=n-1:
        if a[c+1][v+1]==0:
            count=count+1
            c=c+1
            v=v+1
        elif a[c+1][v+1]==1:
            break
    if b-1>=0 and g+1<=n-1:
        if a[g+1][b-1]==0:
            count=count+1
            g=g+1
            b=b-1
        elif a[g+1][b-1]==1:
            break
    if h+1<=n-1 and j-1>=0:
        if a[j-1][h+1]==0:
            count=count+1
            j=j-1
            h=h+1
        elif a[j-1][h+1]==1:
            break
    if k-1>=0 and l-1>=0:
        if a[l-1][k-1]==0:
            count=count+1
            l=l-1
            k=k-1
        elif a[l-1][k-1]==1:
            break

print(count)            #!/bin/python3

import sys


n,k = input().strip().split(' ')
n,k = [int(n),int(k)]
x,y = input().strip().split(' ')
x,y = [int(x)-1,int(y)-1]
a=[]
p=x
w=x
e=x
c=x
g=x
j=x
l=x
q=y
r=y
t=y
v=y
b=y
h=y
k=y
count=0
for a_i in range(n):
        a_t = [0 for j in range(n)]
        a.append(a_t)
for i in range(k):
    x_,y_= map(int,input().strip().split(' '))
    a[x_-1][y_-1]=1

for i in range(n):
    if  p-1>=0:
        if a[p-1][q]==0:
            count=count+1
            p=p-1
        elif a[p-1][q]==1:
            break
    if  w+1<=n-1:
        if a[w+1][q]==0:
            count=count+1
            w=w+1
        elif a[w+1][q]==1:
            break
    if  r+1<=n-1:
        if a[e][r+1]==0:
            count=count+1
            r=r+1
        elif a[e][r+1]==1:
            break
    if  t-1>=0:
        if a[e][t-1]==0:
            count=count+1
            t=t-1
        elif a[e][t-1]==1:
            break
    if c+1<=n-1 and v+1<=n-1:
        if a[c+1][v+1]==0:
            count=count+1
            c=c+1
            v=v+1
        elif a[c+1][v+1]==1:
            break
    if b-1>=0 and g+1<=n-1:
        if a[g+1][b-1]==0:
            count=count+1
            g=g+1
            b=b-1
        elif a[g+1][b-1]==1:
            break
    if h+1<=n-1 and j-1>=0:
        if a[j-1][h+1]==0:
            count=count+1
            j=j-1
            h=h+1
        elif a[j-1][h+1]==1:
            break
    if k-1>=0 and l-1>=0:
        if a[l-1][k-1]==0:
            count=count+1
            l=l-1
            k=k-1
        elif a[l-1][k-1]==1:
            break

print(count)            
